# Generated by Django 5.1.2 on 2025-02-14 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_curso_delete_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAvulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(verbose_name=1500),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.curso')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.usuarioavulso')),
            ],
        ),
        migrations.CreateModel(
            name='AlunoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(verbose_name=1500)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(verbose_name=1500)),
                ('arquivo', models.FileField(upload_to='arquivos/')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('descricao', models.TextField(verbose_name=1500)),
                ('telefone', models.CharField(max_length=15)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.professor')),
            ],
        ),
    ]
