# Generated by Django 5.1.6 on 2025-02-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0003_usuarioavulso_alter_curso_descricao_aluno_alunocurso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professordisciplina',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='professordisciplina',
            name='disciplina',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='ProfessorDisciplina',
        ),
        migrations.DeleteModel(
            name='UsuarioAvulso',
        ),
    ]
