# Generated by Django 5.1.6 on 2025-02-20 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_remove_professordisciplina_professor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='duracao',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='carga_horaria',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='projeto.curso'),
        ),
    ]
