# Generated by Django 5.1.6 on 2025-02-20 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0005_remove_curso_descricao_remove_curso_duracao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunocurso',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='alunocurso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='material',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='curso',
            name='duracao',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.curso'),
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='AlunoCurso',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
