# Generated by Django 5.1.6 on 2025-02-20 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0006_remove_alunocurso_aluno_remove_alunocurso_curso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='carga_horaria',
        ),
        migrations.AddField(
            model_name='curso',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='projeto.curso'),
        ),
    ]
