# Generated by Django 5.1.6 on 2025-02-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0007_remove_disciplina_carga_horaria_curso_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='duracao',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='descricao',
            field=models.TextField(default=200, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
