# Generated by Django 5.1.6 on 2025-02-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0011_criar_curso_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(default='Informática para Internet', editable=False, max_length=100),
        ),
    ]
