# Generated by Django 5.1.6 on 2025-02-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0013_modulo_topico'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='descricao',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
    ]
