# Generated by Django 5.1.6 on 2025-02-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0015_rename_conteudo_topico_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='ordem',
            field=models.IntegerField(),
        ),
    ]
