# Generated by Django 5.1.6 on 2025-02-23 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0016_alter_modulo_nome_alter_modulo_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.disciplina'),
        ),
    ]
