# Generated by Django 5.1.6 on 2025-02-25 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0017_alter_modulo_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='modulo',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='projeto.disciplina'),
        ),
    ]
