# Generated by Django 5.1.6 on 2025-02-25 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0018_remove_curso_descricao_remove_disciplina_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='ordem',
        ),
        migrations.AddField(
            model_name='topico',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='projeto.curso'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topico',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
